#!/usr/bin/env bash
# Generates secrets/ntfy.env with bcrypt-hashed users for NTFY_AUTH_USERS.
# Reads plaintext passwords from .env (NTFY_ADMIN_PASSWORD, NTFY_ALERTMANAGER_PASSWORD).
# Run after changing any ntfy password; then redeploy the ntfy service.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
OUTPUT_FILE="$ROOT_DIR/secrets/ntfy.env"

# Users: "username:role:PASSWORD_ENV_VAR"
# Roles: admin / user
NTFY_USERS=(
    "admin:admin:NTFY_ADMIN_PASSWORD"
    "alertmanager:user:NTFY_ALERTMANAGER_PASSWORD"
)

# ACL: "username:topic:rw|ro|wo|deny"
NTFY_ACCESS=(
    "alertmanager:apphost-critical:rw"
    "alertmanager:apphost-warnings:rw"
)

# ---------------------------------------------------------------------------

if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE not found. Copy .env.example to .env first." >&2
    exit 1
fi

# Load .env without exporting so we can read the password vars
set -a
# shellcheck source=/dev/null
source "$ENV_FILE"
set +a

bcrypt_hash() {
    local password="$1"
    # apachehttpd provides htpasswd; -i reads password from stdin; $2y$ is accepted by Go's bcrypt
    printf '%s\n' "$password" | nix-shell -p apacheHttpd --run 'htpasswd -inBC 10 ""' | tr -d ':\n'
}

auth_users_parts=()
for entry in "${NTFY_USERS[@]}"; do
    IFS=':' read -r username role var_name <<< "$entry"
    password="${!var_name:-}"
    if [[ -z "$password" ]]; then
        echo "ERROR: $var_name is not set in $ENV_FILE" >&2
        exit 1
    fi
    echo "Hashing password for user '$username'..."
    hash=$(bcrypt_hash "$password")
    auth_users_parts+=("${username}:${hash}:${role}")
done

access_parts=()
for rule in "${NTFY_ACCESS[@]}"; do
    access_parts+=("$rule")
done

join_by() { local IFS="$1"; shift; echo "$*"; }

auth_users_value=$(join_by , "${auth_users_parts[@]}")
auth_access_value=$(join_by , "${access_parts[@]}")

mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/update-secrets-ntfy.sh. Do not edit manually!
# Regenerate after any password change and redeploy the ntfy service.
NTFY_AUTH_USERS='${auth_users_value}'
NTFY_AUTH_ACCESS='${auth_access_value}'
EOF

echo "Done. Written to $OUTPUT_FILE"
